name: Keep VPS Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # har 5 minute chalaye
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run ping script
        run: python ping.py
